server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  client_max_body_size 6m;

  location /api/ {
    proxy_pass http://backend:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cookie_path / /;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
