package ma.maarifculture.analytics.service;

import java.math.*;import java.time.*;import java.time.temporal.*;import java.util.*;
import ma.maarifculture.analytics.dto.ForecastDtos.*;import ma.maarifculture.analytics.dto.PageResponse;import ma.maarifculture.analytics.exception.*;import ma.maarifculture.analytics.model.*;import ma.maarifculture.analytics.repository.*;
import org.springframework.beans.factory.annotation.Value;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service @Transactional(readOnly=true)
public class ForecastService {
    private final ProductRepository products;private final OrderItemRepository items;private final SalesForecastRepository forecasts;private final ReorderRecommendationRepository recommendations;private final InventoryService inventory;private final AppSettingRepository settings;private final CurrentUserService currentUser;private final AuditService audit;private final ZoneId zone;
    public ForecastService(ProductRepository products,OrderItemRepository items,SalesForecastRepository forecasts,ReorderRecommendationRepository recommendations,InventoryService inventory,AppSettingRepository settings,CurrentUserService currentUser,AuditService audit,@Value("${maarif.business-timezone}")String zone){this.products=products;this.items=items;this.forecasts=forecasts;this.recommendations=recommendations;this.inventory=inventory;this.settings=settings;this.currentUser=currentUser;this.audit=audit;this.zone=ZoneId.of(zone);}
    @Transactional public ForecastResponse generate(Long productId){Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Produit introuvable : "+productId));List<Double> series=weekly(p);int minimum=setting("forecast.minimum_history_weeks",12),validation=Math.min(setting("forecast.validation_weeks",4),Math.max(1,series.size()/3));ForecastMethod method;double weekly;Double mae=null,mape=null;
        if(series.size()<minimum){method=ForecastMethod.FALLBACK;weekly=series.isEmpty()?0:series.stream().mapToDouble(Double::doubleValue).average().orElse(0);}else{Map<ForecastMethod,Double> scores=new EnumMap<>(ForecastMethod.class);for(ForecastMethod candidate:List.of(ForecastMethod.SIMPLE_MOVING_AVERAGE,ForecastMethod.WEIGHTED_MOVING_AVERAGE,ForecastMethod.EXPONENTIAL_SMOOTHING,ForecastMethod.BASELINE))scores.put(candidate,mae(series,candidate,validation));method=scores.entrySet().stream().min(Map.Entry.comparingByValue()).orElseThrow().getKey();mae=scores.get(method);mape=mape(series,method,validation);weekly=predict(series,method);}
        LocalDate start=LocalDate.now(zone).with(TemporalAdjusters.next(DayOfWeek.MONDAY));LocalDate end=start.plusWeeks(4).minusDays(1);BigDecimal demand=BigDecimal.valueOf(weekly*4).setScale(4,RoundingMode.HALF_UP);String params="historyWeeks="+series.size()+",validationWeeks="+validation+(mape==null?"":",MAPE="+round(mape));String explanation=method==ForecastMethod.FALLBACK?"Historique insuffisant : moyenne des semaines disponibles utilisée comme repli prudent.":"Méthode sélectionnée par MAE sur une période de validation. La prévision est une estimation, pas une garantie.";SalesForecast saved=forecasts.save(new SalesForecast(p,start,end,method,demand,mae==null?null:"MAE",mae==null?null:BigDecimal.valueOf(mae).setScale(6,RoundingMode.HALF_UP),params,explanation));audit.record(currentUser.required(),"FORECAST_GENERATED","SalesForecast",saved.getId(),"method="+method);return response(saved);}
    @Transactional public RecommendationResponse recommend(Long productId){SalesForecast f=forecasts.findFirstByProductIdOrderByGeneratedAtDesc(productId).orElseGet(()->{generate(productId);return forecasts.findFirstByProductIdOrderByGeneratedAtDesc(productId).orElseThrow();});Product p=f.getProduct();int stock=inventory.currentStock(productId);int lead=p.getSupplierLeadTimeDays()!=null?p.getSupplierLeadTimeDays():(p.getSupplier()!=null?p.getSupplier().getDefaultLeadTimeDays():7);BigDecimal daily=f.getPredictedDemand().divide(BigDecimal.valueOf(28),6,RoundingMode.HALF_UP);int safety=daily.multiply(BigDecimal.valueOf(setting("forecast.safety_stock_days",7))).setScale(0,RoundingMode.CEILING).intValue();int point=daily.multiply(BigDecimal.valueOf(lead)).setScale(0,RoundingMode.CEILING).intValue()+safety;int target=daily.multiply(BigDecimal.valueOf(lead+30)).setScale(0,RoundingMode.CEILING).intValue()+safety;int quantity=Math.max(0,target-stock);String explanation="Demande journalière estimée "+daily.setScale(2,RoundingMode.HALF_UP)+", délai "+lead+" jours, stock de sécurité "+safety+". Aucune commande fournisseur n'est créée automatiquement.";ReorderRecommendation r=recommendations.save(new ReorderRecommendation(p,stock,f.getPredictedDemand(),lead,safety,point,quantity,explanation));audit.record(currentUser.required(),"REORDER_RECOMMENDATION_GENERATED","ReorderRecommendation",r.getId(),"quantity="+quantity);return response(r);}
    public PageResponse<RecommendationResponse> recommendations(RecommendationStatus status,int page,int size){var pageable=PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"generatedAt"));return PageResponse.from((status==null?recommendations.findAll(pageable):recommendations.findByStatus(status,pageable)).map(this::response));}
    @Transactional public RecommendationResponse status(Long id,RecommendationStatus status){ReorderRecommendation r=recommendations.findById(id).orElseThrow(()->new ResourceNotFoundException("Recommandation introuvable : "+id));r.changeStatus(status);audit.record(currentUser.required(),"RECOMMENDATION_STATUS_CHANGED","ReorderRecommendation",id,"status="+status);return response(r);}
    private List<Double> weekly(Product p){List<OrderItem> history=items.completedForProduct(p.getId());if(history.isEmpty())return List.of();Map<LocalDate,Double> demand=new TreeMap<>();for(OrderItem i:history){LocalDate week=i.getOrder().getOrderDate().atZone(zone).toLocalDate().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));demand.merge(week,(double)i.getQuantity(),Double::sum);}LocalDate first=demand.keySet().iterator().next(),last=LocalDate.now(zone).with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));List<Double> result=new ArrayList<>();for(LocalDate d=first;!d.isAfter(last);d=d.plusWeeks(1))result.add(demand.getOrDefault(d,0d));return result;}
    private double mae(List<Double>s,ForecastMethod m,int validation){int from=s.size()-validation;double sum=0;for(int i=from;i<s.size();i++)sum+=Math.abs(s.get(i)-predict(s.subList(0,i),m));return sum/validation;}
    private Double mape(List<Double>s,ForecastMethod m,int validation){int from=s.size()-validation;double sum=0;int n=0;for(int i=from;i<s.size();i++)if(s.get(i)>0){sum+=Math.abs((s.get(i)-predict(s.subList(0,i),m))/s.get(i));n++;}return n==0?null:sum/n*100;}
    private double predict(List<Double>s,ForecastMethod m){if(s.isEmpty())return 0;return switch(m){case BASELINE->s.getLast();case SIMPLE_MOVING_AVERAGE->s.subList(Math.max(0,s.size()-4),s.size()).stream().mapToDouble(Double::doubleValue).average().orElse(0);case WEIGHTED_MOVING_AVERAGE->{int n=Math.min(3,s.size());double sum=0,weights=0;for(int i=0;i<n;i++){double w=i+1;sum+=s.get(s.size()-n+i)*w;weights+=w;}yield sum/weights;}case EXPONENTIAL_SMOOTHING->{double value=s.getFirst();for(int i=1;i<s.size();i++)value=.3*s.get(i)+.7*value;yield value;}case FALLBACK->s.stream().mapToDouble(Double::doubleValue).average().orElse(0);};}
    private int setting(String key,int fallback){return settings.findById(key).map(s->{try{return Integer.parseInt(s.getValue());}catch(Exception e){return fallback;}}).orElse(fallback);}private double round(double d){return Math.round(d*100d)/100d;}
    private ForecastResponse response(SalesForecast f){Product p=f.getProduct();return new ForecastResponse(f.getId(),p.getId(),p.getSku(),p.getTitle(),imageUrl(p),f.getPeriodStart(),f.getPeriodEnd(),f.getMethod(),f.getPredictedDemand(),f.getAccuracyMetricName(),f.getAccuracyMetricValue(),f.getGeneratedAt(),f.getModelParameters(),f.getExplanation());}
    private RecommendationResponse response(ReorderRecommendation r){Product p=r.getProduct();return new RecommendationResponse(r.getId(),p.getId(),p.getSku(),p.getTitle(),imageUrl(p),r.getCurrentStock(),r.getPredictedDemand(),r.getLeadTimeDays(),r.getSafetyStock(),r.getReorderPoint(),r.getRecommendedQuantity(),r.getExplanation(),r.getGeneratedAt(),r.getStatus());}
    private String imageUrl(Product p){return p.getImageKey()==null?null:"/api/products/"+p.getId()+"/image";}
}
