create table app_user (
    id bigint generated by default as identity primary key,
    full_name varchar(150) not null,
    email varchar(254) not null unique,
    password_hash varchar(255) not null,
    role varchar(30) not null check (role in ('ADMINISTRATOR', 'MANAGER', 'STOCK_EMPLOYEE')),
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table category (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    parent_id bigint references category(id),
    constraint uk_category_parent_name unique (parent_id, name)
);

create table author (
    id bigint generated by default as identity primary key,
    name varchar(180) not null unique
);

create table publisher (
    id bigint generated by default as identity primary key,
    name varchar(180) not null unique
);

create table supplier (
    id bigint generated by default as identity primary key,
    name varchar(180) not null unique,
    contact_name varchar(150),
    email varchar(254),
    phone varchar(40),
    address varchar(500),
    default_lead_time_days integer not null default 7 check (default_lead_time_days >= 0),
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table product (
    id bigint generated by default as identity primary key,
    sku varchar(80) not null unique,
    isbn varchar(20) unique,
    title varchar(300) not null,
    description varchar(4000),
    publisher_id bigint references publisher(id),
    category_id bigint references category(id),
    supplier_id bigint references supplier(id),
    language varchar(10) not null,
    selling_price numeric(19, 2) not null check (selling_price >= 0),
    purchase_cost numeric(19, 2) check (purchase_cost is null or purchase_cost >= 0),
    minimum_stock_threshold integer not null default 0 check (minimum_stock_threshold >= 0),
    supplier_lead_time_days integer check (supplier_lead_time_days is null or supplier_lead_time_days >= 0),
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table product_author (
    product_id bigint not null references product(id),
    author_id bigint not null references author(id),
    primary key (product_id, author_id)
);

create table sales_order (
    id bigint generated by default as identity primary key,
    external_reference varchar(120) not null,
    order_date timestamp with time zone not null,
    status varchar(30) not null check (status in ('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'REFUNDED')),
    customer_city varchar(120),
    total_amount numeric(19, 2) not null check (total_amount >= 0),
    source varchar(30) not null check (source in ('MANUAL', 'CSV_IMPORT', 'WOOCOMMERCE')),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_sales_order_source_reference unique (source, external_reference)
);

create table order_item (
    id bigint generated by default as identity primary key,
    order_id bigint not null references sales_order(id),
    product_id bigint not null references product(id),
    quantity integer not null check (quantity > 0),
    unit_price numeric(19, 2) not null check (unit_price >= 0),
    discount numeric(19, 2) not null default 0 check (discount >= 0),
    line_total numeric(19, 2) not null check (line_total >= 0),
    constraint ck_order_item_discount check (discount <= unit_price * quantity)
);

create table inventory_movement (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    movement_type varchar(30) not null check (movement_type in (
        'INITIAL_STOCK', 'PURCHASE', 'SALE', 'CUSTOMER_RETURN',
        'SUPPLIER_RETURN', 'DAMAGE', 'CORRECTION'
    )),
    quantity integer not null,
    reason varchar(500) not null,
    related_order_id bigint references sales_order(id),
    created_by_user_id bigint not null references app_user(id),
    occurred_at timestamp with time zone not null default current_timestamp,
    constraint ck_inventory_movement_direction check (
        (movement_type in ('INITIAL_STOCK', 'PURCHASE', 'CUSTOMER_RETURN') and quantity > 0)
        or (movement_type in ('SALE', 'SUPPLIER_RETURN', 'DAMAGE') and quantity < 0)
        or (movement_type = 'CORRECTION' and quantity <> 0)
    ),
    constraint uk_inventory_order_product_type unique (related_order_id, product_id, movement_type)
);

create table stock_alert (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    alert_type varchar(40) not null check (alert_type in (
        'LOW_STOCK', 'OUT_OF_STOCK', 'APPROACHING_STOCKOUT', 'SLOW_MOVING', 'DEAD_STOCK'
    )),
    severity varchar(20) not null check (severity in ('INFO', 'WARNING', 'CRITICAL')),
    explanation varchar(1000) not null,
    status varchar(20) not null default 'OPEN' check (status in ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    created_at timestamp with time zone not null default current_timestamp,
    acknowledged_at timestamp with time zone,
    resolved_at timestamp with time zone,
    acknowledged_by_user_id bigint references app_user(id),
    resolved_by_user_id bigint references app_user(id),
    constraint ck_stock_alert_dates check (
        (acknowledged_at is null or acknowledged_by_user_id is not null)
        and (resolved_at is null or resolved_by_user_id is not null)
    )
);

create table sales_forecast (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    forecast_period_start date not null,
    forecast_period_end date not null,
    forecast_method varchar(40) not null check (forecast_method in (
        'SIMPLE_MOVING_AVERAGE', 'WEIGHTED_MOVING_AVERAGE',
        'EXPONENTIAL_SMOOTHING', 'BASELINE', 'FALLBACK'
    )),
    predicted_demand numeric(19, 4) not null check (predicted_demand >= 0),
    accuracy_metric_name varchar(20),
    accuracy_metric_value numeric(19, 6),
    generated_at timestamp with time zone not null default current_timestamp,
    model_parameters varchar(2000) not null,
    explanation varchar(2000) not null,
    constraint ck_sales_forecast_period check (forecast_period_end >= forecast_period_start),
    constraint uk_forecast_product_period_generated unique (
        product_id, forecast_period_start, forecast_period_end, generated_at
    )
);

create table reorder_recommendation (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    current_stock integer not null,
    predicted_demand numeric(19, 4) not null check (predicted_demand >= 0),
    lead_time_days integer not null check (lead_time_days >= 0),
    safety_stock integer not null check (safety_stock >= 0),
    reorder_point integer not null check (reorder_point >= 0),
    recommended_quantity integer not null check (recommended_quantity >= 0),
    explanation varchar(2000) not null,
    generated_at timestamp with time zone not null default current_timestamp,
    status varchar(30) not null default 'PROPOSED' check (status in ('PROPOSED', 'ACKNOWLEDGED', 'DISMISSED', 'ORDERED'))
);

create table import_job (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    file_checksum varchar(64) not null,
    import_type varchar(30) not null check (import_type in ('SALES_CSV', 'SALES_EXCEL', 'WOOCOMMERCE')),
    status varchar(30) not null check (status in ('VALIDATING', 'READY', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', 'DUPLICATE')),
    total_rows integer not null default 0 check (total_rows >= 0),
    successful_rows integer not null default 0 check (successful_rows >= 0),
    failed_rows integer not null default 0 check (failed_rows >= 0),
    user_id bigint not null references app_user(id),
    started_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone,
    error_report_location varchar(500),
    constraint uk_import_type_checksum unique (import_type, file_checksum),
    constraint ck_import_row_counts check (successful_rows + failed_rows <= total_rows)
);

create table import_job_error (
    id bigint generated by default as identity primary key,
    import_job_id bigint not null references import_job(id),
    row_number integer not null check (row_number > 0),
    field_name varchar(100),
    error_code varchar(80) not null,
    message varchar(1000) not null,
    rejected_value varchar(500)
);

create table audit_log (
    id bigint generated by default as identity primary key,
    user_id bigint references app_user(id),
    action varchar(100) not null,
    entity_type varchar(100) not null,
    entity_id varchar(100),
    occurred_at timestamp with time zone not null default current_timestamp,
    metadata varchar(4000)
);

create index idx_product_title on product(title);
create index idx_product_category on product(category_id);
create index idx_sales_order_date_status on sales_order(order_date, status);
create index idx_order_item_product on order_item(product_id);
create index idx_inventory_movement_product_time on inventory_movement(product_id, occurred_at);
create index idx_stock_alert_status_type on stock_alert(status, alert_type);
create index idx_forecast_product_period on sales_forecast(product_id, forecast_period_start);
create index idx_reorder_product_status on reorder_recommendation(product_id, status);
create index idx_audit_log_time on audit_log(occurred_at);

