export const CATALOG_PRODUCTS = [
  {
    sku: "LIV-000184",
    title: "La Boîte à merveilles",
    author: "Ahmed Sefrioui",
    category: "Roman",
    language: "Français",
    price: 78,
    stock: 42,
    threshold: 8,
    active: true,
  },
  {
    sku: "LIV-000231",
    title: "Le Pain nu",
    author: "Mohamed Choukri",
    category: "Roman",
    language: "Français",
    price: 92,
    stock: 18,
    threshold: 6,
    active: true,
  },
  {
    sku: "LIV-000417",
    title: "L’Étranger",
    author: "Albert Camus",
    category: "Roman",
    language: "Français",
    price: 69,
    stock: 31,
    threshold: 10,
    active: true,
  },
  {
    sku: "LIV-000538",
    title: "Antigone",
    author: "Jean Anouilh",
    category: "Scolaire",
    language: "Français",
    price: 48.5,
    stock: 5,
    threshold: 8,
    active: true,
  },
  {
    sku: "LIV-000619",
    title: "Les Misérables — Tome I",
    author: "Victor Hugo",
    category: "Roman",
    language: "Français",
    price: 115,
    stock: 0,
    threshold: 5,
    active: true,
  },
  {
    sku: "LIV-000704",
    title: "طفولة في مراكش",
    author: "عبد المجيد بن جلون",
    category: "Roman",
    language: "Arabe",
    price: 64,
    stock: 24,
    threshold: 7,
    active: true,
  },
  {
    sku: "LIV-000819",
    title: "Le Maroc raconté aux enfants",
    author: "Leïla Slimani",
    category: "Jeunesse",
    language: "Français",
    price: 129,
    stock: 16,
    threshold: 6,
    active: true,
  },
  {
    sku: "LIV-000926",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    category: "Jeunesse",
    language: "Anglais",
    price: 84,
    stock: 9,
    threshold: 5,
    active: true,
  },
  {
    sku: "LIV-001014",
    title: "موسم الهجرة إلى الشمال",
    author: "الطيب صالح",
    category: "Roman",
    language: "Arabe",
    price: 72,
    stock: 3,
    threshold: 6,
    active: true,
  },
  {
    sku: "LIV-001108",
    title: "Atlas des roches du Maroc",
    author: "Samira El Fassi",
    category: "Essai",
    language: "Français",
    price: 245,
    stock: 18,
    threshold: 4,
    active: true,
  },
  {
    sku: "LIV-001237",
    title: "Grammaire française avancée",
    author: "Nadia Berrada",
    category: "Scolaire",
    language: "Français",
    price: 96,
    stock: 14,
    threshold: 5,
    active: true,
  },
  {
    sku: "LIV-001355",
    title: "Introduction à la philosophie",
    author: "Karim Amrani",
    category: "Essai",
    language: "Français",
    price: 105,
    stock: 12,
    threshold: 5,
    active: false,
  },
  {
    sku: "LIV-001468",
    title: "Dictionnaire arabe–français",
    author: "Collectif Maarif",
    category: "Référence",
    language: "Arabe",
    price: 189,
    stock: 16,
    threshold: 4,
    active: true,
  },
  {
    sku: "LIV-001572",
    title: "Lecture et compréhension CM2",
    author: "Salma Idrissi",
    category: "Scolaire",
    language: "Français",
    price: 54,
    stock: 10,
    threshold: 8,
    active: true,
  },
  {
    sku: "LIV-001684",
    title: "Dreams of Trespass",
    author: "Fatema Mernissi",
    category: "Essai",
    language: "Anglais",
    price: 138,
    stock: 7,
    threshold: 5,
    active: true,
  },
  {
    sku: "LIV-001793",
    title: "ذاكرة للنسيان",
    author: "محمود درويش",
    category: "Essai",
    language: "Arabe",
    price: 79,
    stock: 0,
    threshold: 5,
    active: false,
  },
  {
    sku: "LIV-001847",
    title: "Contes du Maroc",
    author: "Halima Hamdane",
    category: "Jeunesse",
    language: "Français",
    price: 75,
    stock: 22,
    threshold: 7,
    active: true,
  },
  {
    sku: "LIV-001934",
    title: "The Moor’s Account",
    author: "Laila Lalami",
    category: "Roman",
    language: "Anglais",
    price: 145,
    stock: 11,
    threshold: 5,
    active: true,
  },
];

export const CATALOG_PERMISSIONS = {
  Administrateur: { view: true, edit: true, create: true, disable: true },
  Gestionnaire: { view: true, edit: true, create: true, disable: true },
  "Employé de stock": {
    view: true,
    edit: false,
    create: false,
    disable: false,
  },
};

export const formatMad = (value) =>
  `${value.toLocaleString("fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} MAD`;

