import { useEffect, useId, useState } from "react";
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowClockwise,
  ArrowRight,
  ArrowUp,
  Bell,
  Books,
  BookOpen,
  CalendarBlank,
  CaretDown,
  ChartBar,
  ChartLineUp,
  CheckCircle,
  CircleNotch,
  CloudArrowUp,
  Cube,
  CurrencyDollar,
  DownloadSimple,
  FileText,
  FileCsv,
  FloppyDisk,
  GearSix,
  Eye,
  List,
  MapPin,
  MagnifyingGlass,
  Key,
  PencilSimple,
  Plus,
  Prohibit,
  ShoppingBagOpen,
  ShoppingCart,
  Shield,
  SignOut,
  TrendUp,
  Truck,
  User,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  X,
} from "@phosphor-icons/react";
import {
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";


export const ORDERS = [
  {
    reference: "CMD-2026-1842",
    isoDate: "2026-08-27",
    date: "27 août 2026 à 16:38",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Casablanca",
    itemCount: 3,
    total: 418.0,
  },
  {
    reference: "CMD-2026-1841",
    isoDate: "2026-08-27",
    date: "27 août 2026 à 15:52",
    status: "En préparation",
    source: "Site web",
    city: "Rabat",
    itemCount: 5,
    total: 672.5,
  },
  {
    reference: "CMD-2026-1840",
    isoDate: "2026-08-27",
    date: "27 août 2026 à 14:16",
    status: "Expédiée",
    source: "Téléphone",
    city: "Marrakech",
    itemCount: 2,
    total: 286.0,
  },
  {
    reference: "CMD-2026-1839",
    isoDate: "2026-08-27",
    date: "27 août 2026 à 11:44",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Casablanca",
    itemCount: 1,
    total: 78.0,
  },
  {
    reference: "CMD-2026-1838",
    isoDate: "2026-08-26",
    date: "26 août 2026 à 18:21",
    status: "En préparation",
    source: "Site web",
    city: "Tanger",
    itemCount: 4,
    total: 519.9,
  },
  {
    reference: "CMD-2026-1837",
    isoDate: "2026-08-26",
    date: "26 août 2026 à 16:05",
    status: "Annulée",
    source: "Site web",
    city: "Fès",
    itemCount: 2,
    total: 194.0,
  },
  {
    reference: "CMD-2026-1836",
    isoDate: "2026-08-26",
    date: "26 août 2026 à 10:32",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Casablanca",
    itemCount: 6,
    total: 845.75,
  },
  {
    reference: "CMD-2026-1835",
    isoDate: "2026-08-25",
    date: "25 août 2026 à 17:48",
    status: "Expédiée",
    source: "Téléphone",
    city: "Agadir",
    itemCount: 3,
    total: 362.5,
  },
  {
    reference: "CMD-2026-1834",
    isoDate: "2026-08-25",
    date: "25 août 2026 à 11:08",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Mohammédia",
    itemCount: 2,
    total: 207.0,
  },
  {
    reference: "CMD-2026-1833",
    isoDate: "2026-08-23",
    date: "23 août 2026 à 13:27",
    status: "Livrée",
    source: "Site web",
    city: "Rabat",
    itemCount: 7,
    total: 968.0,
  },
  {
    reference: "CMD-2026-1832",
    isoDate: "2026-08-22",
    date: "22 août 2026 à 19:04",
    status: "En préparation",
    source: "Téléphone",
    city: "Casablanca",
    itemCount: 2,
    total: 245.0,
  },
  {
    reference: "CMD-2026-1831",
    isoDate: "2026-08-20",
    date: "20 août 2026 à 09:42",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Tétouan",
    itemCount: 4,
    total: 536.5,
  },
  {
    reference: "CMD-2026-1778",
    isoDate: "2026-08-12",
    date: "12 août 2026 à 15:36",
    status: "Livrée",
    source: "Site web",
    city: "Marrakech",
    itemCount: 3,
    total: 429.0,
  },
  {
    reference: "CMD-2026-1689",
    isoDate: "2026-07-29",
    date: "29 juillet 2026 à 17:18",
    status: "Livrée",
    source: "Boutique Maarif",
    city: "Casablanca",
    itemCount: 5,
    total: 714.0,
  },
  {
    reference: "CMD-2026-1654",
    isoDate: "2026-07-18",
    date: "18 juillet 2026 à 10:07",
    status: "Annulée",
    source: "Téléphone",
    city: "Fès",
    itemCount: 1,
    total: 92.0,
  },
];

export function OrderStatus({ status }) {
  const tone =
    {
      Livrée: "delivered",
      Expédiée: "shipped",
      "En préparation": "processing",
      Annulée: "cancelled",
      Brouillon: "draft",
    }[status] ?? "draft";
  return (
    <span className={`catalog-status order-status order-status--${tone}`}>
      {status}
    </span>
  );
}

const ORDER_DETAILS = {
  "CMD-2026-1841": {
    lines: [
      {
        product: "Le Pain nu",
        sku: "LIV-000231",
        quantity: 2,
        unitPrice: 58.0,
        discount: 0,
        lineTotal: 116.0,
      },
      {
        product: "Antigone",
        sku: "LIV-000538",
        quantity: 1,
        unitPrice: 92.0,
        discount: 5,
        lineTotal: 87.4,
      },
      {
        product: "طفولة في مراكش",
        sku: "LIV-000704",
        quantity: 1,
        unitPrice: 94.0,
        discount: 0,
        lineTotal: 94.0,
      },
      {
        product: "Les Misérables — Tome I",
        sku: "LIV-000619",
        quantity: 1,
        unitPrice: 375.1,
        discount: 0,
        lineTotal: 375.1,
      },
    ],
    movements: [
      {
        id: "MVT-2026-0865",
        date: "27 août 2026 à 16:02",
        product: "Le Pain nu",
        sku: "LIV-000231",
        type: "Sortie réservée",
        quantity: -2,
        balance: 18,
      },
      {
        id: "MVT-2026-0864",
        date: "27 août 2026 à 16:02",
        product: "Antigone",
        sku: "LIV-000538",
        type: "Sortie réservée",
        quantity: -1,
        balance: 5,
      },
      {
        id: "MVT-2026-0863",
        date: "27 août 2026 à 16:01",
        product: "طفولة في مراكش",
        sku: "LIV-000704",
        type: "Sortie réservée",
        quantity: -1,
        balance: 24,
      },
      {
        id: "MVT-2026-0862",
        date: "27 août 2026 à 16:01",
        product: "Les Misérables — Tome I",
        sku: "LIV-000619",
        type: "Sortie réservée",
        quantity: -1,
        balance: 0,
      },
    ],
  },
  "CMD-2026-1842": {
    lines: [
      {
        product: "La Boîte à merveilles",
        sku: "LIV-000184",
        quantity: 1,
        unitPrice: 78.0,
        discount: 0,
        lineTotal: 78.0,
      },
      {
        product: "L’Étranger",
        sku: "LIV-000417",
        quantity: 1,
        unitPrice: 140.0,
        discount: 10,
        lineTotal: 126.0,
      },
      {
        product: "Grand dictionnaire français",
        sku: "LIV-000912",
        quantity: 1,
        unitPrice: 214.0,
        discount: 0,
        lineTotal: 214.0,
      },
    ],
    movements: [
      {
        id: "MVT-2026-0861",
        date: "27 août 2026 à 16:42",
        product: "La Boîte à merveilles",
        sku: "LIV-000184",
        type: "Sortie vente",
        quantity: -1,
        balance: 42,
      },
      {
        id: "MVT-2026-0860",
        date: "27 août 2026 à 16:42",
        product: "L’Étranger",
        sku: "LIV-000417",
        type: "Sortie vente",
        quantity: -1,
        balance: 31,
      },
      {
        id: "MVT-2026-0859",
        date: "27 août 2026 à 16:41",
        product: "Grand dictionnaire français",
        sku: "LIV-000912",
        type: "Sortie vente",
        quantity: -1,
        balance: 11,
      },
    ],
  },
};

export function detailsForOrder(order) {
  if (ORDER_DETAILS[order.reference]) return ORDER_DETAILS[order.reference];
  return {
    lines: [
      {
        product: "Articles de librairie",
        sku: order.reference,
        quantity: order.itemCount,
        unitPrice: order.itemCount ? order.total / order.itemCount : 0,
        discount: 0,
        lineTotal: order.total,
      },
    ],
    movements: order.itemCount
      ? [
          {
            id: `MVT-${order.reference}`,
            date: order.date,
            product: "Articles de librairie",
            sku: order.reference,
            type: "Sortie commande",
            quantity: -order.itemCount,
            balance: 12,
          },
        ]
      : [],
  };
}
